### ISSUE TITLE
Gnome 3.16 support

### ISSUE THREAD

**Issue by Isgar** [eonpatapon/gnome-shell-extension-transmission-daemon#35]
Simply adding 3.16 to metadata.json makes the extension work.

The only problem is that the UI text is grey on darker grey, the contrast is too low. That not only makes the torrent information harder to read, but also suggests that the clickable buttons are disabled even though they are working.

**Comment by ouafnico** [comment]
same thing here.

**Comment by TheKevJames** [comment]
@lsgar @ouafnico I've just taken over maintenance of this project on [my GitHub fork](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon) as well as the [extensions.gnome.org project](https://extensions.gnome.org/extension/365/transmission-daemon-indicator/). The original maintainer no longer works on this project and I have no plans to re-introduce support for versions of Gnome Shell below 3.20. Installing from GitHub tag [3.0.0](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon/releases/tag/3.0.0) should have the [best chance of working correctly on Gnome Shell 3.16](https://github.com/TheKevJames/gnome-shell-extension-transmission-daemon#older-versions-of-gnome-shell).
