### ISSUE TITLE
Rename org.gnome.shell.extensions.mediaplayer.gschema.xml

### ISSUE THREAD

**Issue by smcdougall** [eonpatapon/gnome-shell-extension-transmission-daemon#36]
The file: 

> org.gnome.shell.extensions.mediaplayer.gschema.xml

Should be renamed to something like:

> org.gnome.shell.extensions.transmission-daemon.gschema.xml

In order to avoid conflicts with the original mediaplayer extension on a system-wide installation (such as one from the AUR).

**Comment by eonpatapon** [comment]
Sorry, what is the original mediaplayer extension ?

**Comment by smcdougall** [comment]
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer

Sorry, I should have been clearer. I'm assuming you used your other project as a base for this one, but you forgot to rename the schema file. It still has "mediaplayer" in its name. This makes it conflict with mediaplayer if you try to install both extensions system-wide because they both want to write to the file:

> /usr/share/glib-2.0/schemas/org.gnome.shell.extensions.mediaplayer.gschema.xml

A simple rename of the schema file should fix the issue. =D

**Comment by eonpatapon** [comment]
Right! I didn't get that one :)

I'll fix this

**Comment by smcdougall** [comment]
I discovered it through this [unofficial package](http://aur.archlinux.org/packages/gnome-shell-extension-transmission-daemon-git/) on the AUR.  I informed them of the issue, but I thought the best solution was just to let you know about it.  Thanks for the quick fix!  I'll tell them they can update their pkgbuild.

**Comment by eonpatapon** [comment]
Good catch !

**Comment by smcdougall** [comment]
Oh, and *really* nice extension.  I just set up a transmission-daemon on my home server a few days ago.  This is the perfect companion for it. =D
