### ISSUE TITLE
https://extensions.gnome.org doesn't work, old code?

### ISSUE THREAD

**Issue by KeNaCo** [eonpatapon/gnome-shell-extension-transmission-daemon#37]
Ok, I wrote this as an issue.. Its maybe gnome problem or my side problem, but for sure.
I have Gnome 3.16, which you support, but it fail install from page.. 
https://extensions.gnome.org/extension/365/transmission-daemon-indicator/

**Comment by eonpatapon** [comment]
Yes the code is not up to date

**Comment by eonpatapon** [comment]
Last code uploaded
