### ISSUE TITLE
Popup closes when Add Torrent text box is clicked

### ISSUE THREAD

**Issue by donny85** [eonpatapon/gnome-shell-extension-transmission-daemon#40]
Affects at least Gnome Shell 3.16 and 3.18

**Steps to reproduce:**
1) click the extension icon on the panel
-> extension popup opens
2) click the "[+] Add Torrent" icon at the top controls area
-> new textarea appears ("Torrent URL or Magnet link")
3) click into the textarea to set focus to it
-> the whole PopupBaseMenuItem is activated and the popup is closed

**Possible fix:**
disable `activate` signal in TorrentsControls class

**Comment by atrias** [comment]
This happens to me as well. 
I also left a comment about this on the gnome extension page.

**Comment by ItachiSan** [comment]
Still present, affects me also..

**Comment by eonpatapon** [comment]
Fixed by the last commit on version 3.20

See #46
