### ISSUE TITLE
Can't change the connect URL

### ISSUE THREAD

**Issue by tliron** [eonpatapon/gnome-shell-extension-transmission-daemon#43]
For complicated reasons I am not using the default /transmission/rpc/ URL for my connection, and unfortunately I can't change it in this plugin.

**Comment by eonpatapon** [comment]
What's your url ?

**Comment by tliron** [comment]
The URL I prefer "/rpc" instead of "/transmission/rpc" (note that in setting.json, you just set the base URL, i.e. "/transmission/", but transmission-daemon will add "/rpc" to it).

**Comment by eonpatapon** [comment]
You can change the /transmission/ to / in gsettings.

$ gsettings --schemadir .local/share/gnome-shell/extensions/transmission-daemon@patapon.info/schemas/ set org.gnome.shell.extensions.transmission-daemon url '/'
$ gsettings --schemadir .local/share/gnome-shell/extensions/transmission-daemon@patapon.info/schemas/ get org.gnome.shell.extensions.transmission-daemon url
'/'

Restart the shell

**Comment by tliron** [comment]
Cool, thanks for the guide. I am suggesting that it should be added to the settings UI, just like you can change the port.

**Comment by eonpatapon** [comment]
This is a very special case, so I don't think it's useful to have that in the UI for now
