### ISSUE TITLE
Can't paste torrent URL

### ISSUE THREAD

**Issue by ouafnico** [eonpatapon/gnome-shell-extension-transmission-daemon#46]
Hello
Since Gnome 3.18, same on 3.20, when I clic on the blank field to paste an URL, the extension close.

So... no usable to upload a new torrent :(

**Comment by ducklord** [comment]
Have the same issue. Got the error after upgrading to Ubuntu 16.04 LTS, which provides Gnome 3.18.5.

**Comment by ducklord** [comment]
My first assumption is that the "click event" triggered when selecting the text input field, has changed behaviour to "bubble" through the input field, in later versions of gnome-shell. I am not a Gnome-shell extension coder, so is having a hard time debugging this.

**Comment by ducklord** [comment]
Until there is a stable fix, here is a "work around". Click and hold the mouse button on the text input field, move the mouse up to the "+" button, and release the mouse. Now the input field has focus, and you can paste the text.

**Comment by eonpatapon** [comment]
@ducklord: fixed it for 3.20. I have no 3.18 to test again. Just add 3.18 in the metadata.json file to see if it works for you

**Comment by ducklord** [comment]
@eonpatapon: It works. :) Thank you very much.
